main: it.davide.stands.StandManager
name: StandsCore
version: 1.8.2
author: [EscanorTargaryen]

api-version: 1.15
depend: [CmcSkyBlock]
softdepend: [Vault]

commands:
  stand:
    description: Command
  newspaper:
    description: Command

