# Roadside Shop config
# For help see the official wiki

#  --Plugin settings--

#The time in seconds to set an item as sponsored after already placing one
sponsor-time: 300

#The number of the unlocked slots (must be positive and less than 15)
unlocked-slot: 13

#  --Messages--

#The message to be shown when showing the price
#Placeholders:
# <value> - The price of the item
price-message: 'Price: <value>'

#The title of the item indicating an unlocked slot
unlocked-slot-panel-title: '&6Shop Slot'

#The lore of the item indicating an unlocked slot
unlocked-slot-lore:
  - "&7Click to add an item!"

#The title of the item indicating a locked slot
locked-slot-panel-title: '&cLocked Slot'

#The lore of the item indicating a locked slot
locked-slot-lore:
  - "&7This slot is locked"

#The message of when you put an item up for sale
#Placeholders:
# <type> - The type of the item
# <amount> - The amount of the item
# <price> - The price of the item
put-item: '&6You put &a<type>x<amount>&6 for&a <price>'

#The message of when you put an item up for sale and set it as sponsored
#Placeholders:
# <type> - The type of the item
# <amount> - The amount of the item
# <price> - The price of the item
sponsor-set: '&6You set this item as a sponsor'

#Message that is shown when there is no items to display in the newspaper
no-adv: '&4There aren t advertisement now, try later'

#Message that is shown when you remove an item from the shop
#Placeholders:
# <type> - The type of the item
# <amount> - The amount of the item
# <price> - The price of the item
remove-item: '&6You removed&a <type>x<amount> &6 for &a <price> &6 from your shop'

#Message that is shown when you buy an item from a shop
#Placeholders:
# <type> - The type of the item
# <amount> - The amount of the item
# <price> - The price of the item
# <name> - The name of the owner of the shop
bought-message: '&6 You bought &a <type>x<amount> &6for&a <price>CC &6 from <name> s shop'

#Message that is shown when you sell an item from your shop
#Placeholders:
# <type> - The type of the item
# <amount> - The amount of the item
# <price> - The price of the item
# <name> - The name of the customer
seller-message: '&6You sold &a <type>x<amount> &6for&a <price>CC &6to <name>'

item-sale-lore:
  #In addition to the lore of the item when it is for sale, displayed by the shop owner
  #Placeholders:
  # <price-message> - The price of the item but
  # <price> - The price of the item
  seller:
    - ""
    - "<price-message>"
    - ""
    - "&6Click to edit item"

  #In addition to the lore of the item when it is for sale, displayed by the buyer
  #Placeholders:
  # <price-message> - The price of the item but
  # <price> - The price of the item
  buyer:
    - ""
    - "<price-message>"
    - ""
    - "&6Click to buy the item"

  #In addition to the lore of the item when it is for sale and sponsored, displayed by the shop owner
  #Placeholders:
  # <price-message> - The price of the item but
  # <price> - The price of the item
  seller-sponsor:
    - ""
    - "<price-message>"
    - ""
    - "&cSponsored Item"
    - ""
    - "&6Click to edit item"

  #In addition to the lore of the item when it is for sale and sponsored, displayed by the buyer
  #Placeholders:
  # <price-message> - The price of the item but
  # <price> - The price of the item
  buyer-sponsor:
    - ""
    - "<price-message>"
    - ""
    - "&cSponsored Item"
    - ""
    - "&6Click to buy the item"

  #In addition to the lore of the item when it is in the newspaper
  #Placeholders:
  # <price-message> - The price of the item but
  # <price> - The price of the item
  # <ownerName> - The owner name of the shop
  newspaper:
    - ""
    - "<price-message>"
    - ""
    - "&eOwner: &7<ownerName>"
    - ""
    - "&6Click to checkout the shop"

#The title of the shop
#Placeholders:
# <playerName> - The name of the player
shop-title: "&1<playerName>'s shop"

item-settings:
  title: "&1Sale Settings"

#Change the button that sets whether an items can be sponsored or not
#Placeholders:
# <minutes> - How often can you put an object as sponsored
sponsor-button:
  #Button title
  title: "&6Sponsor item"

  #Description of the button when you set the item as sponsored (there was no item as sponsored precendently)
  sponsoring:
    - ""
    - "&aThe item will be sponsored."
    - "&7Sponsoring an item shows it on the newspaper."
    - "&7You can sponsor an item every <minutes> minutes."
    - ""
    - "&6Click to unsponsor"

  #Description of the button when you set the item as sponsored (there is an item as sponsored precendently)
  sponsoring-change:
    - ""
    - "&aThe item will be sponsored."
    - "&7Sponsoring an item shows it on the newspaper."
    - "&7You can sponsor an item every <minutes> minutes."
    - ""
    - "&4N.B.: &cYou already have a sponsored item. Sponsoring"
    - "&cthis item is going to unsponsor the other one."
    - ""
    - "&6Click to unsponsor"

  #Description of the button when you have not set the item as sponsored (there was no item as sponsored precendently)
  not-sponsoring:
    - ""
    - "&cThe item isn't sponsored at the moment."
    - "&7Sponsoring an item shows it on the newspaper."
    - "&7You can sponsor an item every <minutes> minutes."
    - ""
    - "&6Click to sponsor"

  #Description of the button when you have not set the item as sponsored (there is an item as sponsored precendently)
  not-sponsoring-change:
    - ""
    - "&cThe item isn't sponsored at the moment."
    - "&7Sponsoring an item shows it on the newspaper."
    - "&7You can sponsor an item every <minutes> minutes."
    - ""
    - "&4N.B.: &cYou already have a sponsored item. Sponsoring"
    - "&cthis item is going to unsponsor the other one."
    - ""
    - "&6Click to sponsor"

  #Button description when you have to wait some time before setting an item as sponsored
  #Placeholders:
  # <missToSponsor> - Time until you can sponsor another item
  wait:
    - ""
    - "&4You've already sponsored an item."
    - "&4Wait <missToSponsor> minutes to sponsor another item."
    - ""
    - "&7Sponsoring an item shows it on the newspaper."
    - "&7You can sponsor an item every <minutes> minutes."

newspaper:
  title: "&6Newspaper"
  arrows:
    right:
      title: "&6Change Page"
      lore:
        - ""
        - "&7Click to view next page"
    left:
      title: "&6Change Page"
      lore:
        - ""
        - "&7Click to view next page"