price-message: 'Price: <value> CC'
unlocked-slot-panel-title: 'Stand Slot'
unlocked-slot-lore:
- Add
- Something
locked-slot-panel-title: 'Unlocked Slot'
locked-slot-lore:
- not today
- Something
put-item: '&6You put &a<type>x<amount>&6 for&a <price>CC'
sponsor-set: '&6You setted this item as a sponsor'
no-adv: '&4There aren t advertisement now, try later'
remove-item: '&6You removed&a <type>x<amount> &6 for &a <price>CC &6 from your stand'
sponsor-item-set: '&6You setted&a <type>x<amount> &6 for &a <price>CC &6 as a sponsor'
bought-message: '&6 You bought &a <type>x<amount> &6for&a <price>CC &6 from <name> s stand'
seller-message: '&6You sold &a <type>x<amount> &6for&a <price>CC &6to <name>'
sponsor-time-mills: 5000