main: it.escanortargaryen.roadsideshop.RoadsideShops
name: ${project.name}
version: ${project.version}
author: [ EscanorTargaryen ]

api-version: 1.15
depend: [ Vault ]

permissions:
  roadsideshops.admin.sponsortimebypass:
    description: bypass sponsor time
    default: op
  roadsideshops.admin.editshops:
    description: permission to edit the shops of others with command /roadsideshopsadmin <player>
    default: op
  roadsideshops.shopcommand:
    description: open shop GUI
    default: true
  roadsideshops.newspapercommand:
    description: open newspaper GUI
    default: true
