main: it.escanortargaryen.roadsideshop.RoadsideShops
name: ${project.name}
version: ${project.version}
author: [EscanorTargaryen]

api-version: 1.15
depend: [Vault]

permissions:
  stand.bypass.sponsortime:
    description: if have this permission dont wait before select a new item to sponsor
    default: op