main: it.escanortargaryen.roadsideshop.RoadsideShops
name: ${project.name}
version: ${project.version}
author: [ EscanorTargaryen ]

api-version: 1.15
depend: [ Vault ]

permissions:
  roadsideshops.admin.sponsortimebypass:
    description: if have this permission dont wait before select a new item to sponsor
    default: op
  roadsideshops.admin.editshops:
    description: permission to edit the shops of others
    default: op
  roadsideshops.shopcommand:
    description: can use the command to see the shops
    default: true
  roadsideshops.newspapercommand:
    description: can use the command to see the newspaper
    default: true
