main: it.davide.stands.StandManager
name: StandCore
version: 1.8.2
author: [EscanorTargaryen]

api-version: 1.15
depend: [CmcSkyBlock]
softdepend: [Vault]

commands:
  stand:
    description: Command
  newspaper:
    description: Command

permissions:
  stand.bypass.sponsortime:
    description: if have this permission dont wait before select a new item to sponsor
    default: op